services:
  - type: web
    name: hiring-process-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: EMAIL_SERVICE
        value: gmail
      - key: GMAIL_EMAIL
        sync: false
      - key: GMAIL_PASSWORD
        sync: false